spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/financial-targets-db"
    username: postgres
    password: G~w<Yq=&fU;93kNLZ

server:
  port: 8082
  servlet:
    contextPath: /account-api

info:
  app:
    name: Financial Targets Account Service
    version: '0.0.1-SNAPSHOT'